// section3/w5_React/src/components/todolist/TodoItem.jsx
import React from 'react'
import context from './context'
function TodoItem({ item, index }) {
    const {remove,complete} = React.useContext(context);
    // console.log('TodoItem.value',value)
    return (
        // <context.Consumer>
        //     {
        //         ({remove,complete}) => {
        //             return (
                        <tr>
                            <th scope="row">{index + 1}</th>
                            <td>{item.todo}</td>
                            {/* <td>{item.done ? '是' : '否'}</td> */}
                            <td>{item.done ? <button className="btn btn-outline-secondary" disabled>是</button> : <button className="btn btn-outline-secondary" disabled >否</button>}</td>
                            <td>
                                <button type="button" className="btn btn-primary" onClick={complete.bind(null, item.id)}>完成</button>
                                <button type="button" className="btn btn-danger" onClick={remove.bind(null, item.id)}>删除</button>
                            </td>
                        </tr>
        //             )
        //         }
        //     }

        // </context.Consumer>
    )
}



export default TodoItem;

// section3/w3_VueCLI/app/src/components/Todolist/TodoItem.vue
<template>
  <tr @click="selectItem(item.id)">
    <td><input type="checkbox" :checked="selectIds.includes(item.id)" /></td>
    <th scope="row">{{ idx + 1 }}</th>
    <td>{{ item.todo }}</td>
    <!-- <td v-once>{{formatDate(item.addtime)}}</td> -->
    <td>{{ date }}</td>
    <td>{{ item.done ? "是" : "否" }}</td>
    <td>
      <button
        class="btn btn-outline-primary btn-sm"
        v-on:click.stop="completeItem(item.id)"
      >
        {{ item.done ? "取消" : "完成" }}
      </button>
      <button
        class="btn btn-outline-danger btn-sm"
        v-on:click.stop="removeItem(item.id)"
      >
        删除
      </button>
    </td>
  </tr>
</template>
<script>
export default {
  name: "TodoItem",
  props: ["item", "idx"],
  inject: ["selectItem", "selectIds"],
  computed: {
    date() {
      // console.log('computed.date')
      return new Date(this.item.addtime).toLocaleDateString();
    },
  },
  methods: {
    completeItem(id) {
      Bus.$emit("complete", id);
    },
    removeItem(id) {
      Bus.$emit("remove", id);
    },
    formatDate(d) {
      console.log("formatDate");
      return new Date(d).toLocaleDateString();
    },
  },
};
</script>
<style>
</style>
