// section3/w5_React/src/components/todolist/Todolist.jsx
import React from 'react'

import TodoForm from './TodoForm'
import TodoContent from './TodoContent'
import TodoFoot from './TodoFoot'

import context from './context'
import 'bootstrap/dist/css/bootstrap.css'

class Todolist extends React.Component {
    // constructor() {
    //     super()

    //     console.log('Todolist', this)
    //     // 定义组件状态（数据）
    //     this.state = {
    //         // count:1,
    //         datalist: [
    //             {
    //                 id: 1,
    //                 todo: '顶个小目标，赚它一个亿',
    //                 done: false,
    //                 addtime: Date.now() + 100
    //             },
    //             {
    //                 id: 2,
    //                 todo: '迎娶白富美，达到巅峰状态',
    //                 done: true,
    //                 addtime: Date.now() + 300
    //             },
    //             {
    //                 id: 3,
    //                 todo: '出任CEO，达到疯癫状态',
    //                 done: false,
    //                 addtime: Date.now() + 600
    //             },
    //         ]
    //     }

    //     // this.addItem = this.addItem.bind(this);
    //     // this.completeItem = this.completeItem.bind(this);
    //     // this.removeItem = this.removeItem.bind(this);
    // }

    state = {
        // count:1,
        datalist: [
            {
                id: 1,
                todo: '顶个小目标，赚它一个亿',
                done: false,
                addtime: Date.now() + 100
            },
            {
                id: 2,
                todo: '迎娶白富美，达到巅峰状态',
                done: true,
                addtime: Date.now() + 300
            },
            {
                id: 3,
                todo: '出任CEO，达到疯癫状态',
                done: false,
                addtime: Date.now() + 600
            },
        ]
    }

    // 在这里定义的发方法会成为原型方法
    addItem = (todo) => {
        const newItem = {
            id: parseInt(Math.random() * 10000),
            todo,
            done: false,
            addtime: Date.now()
        }

        // react中不能直接修改原来的状态，而是使用一个新的值去覆盖
        const datalist = [...this.state.datalist];
        datalist.unshift(newItem)
        this.setState({
            datalist
        })
    }
    // 定义时使用箭头函数
    completeItem = (id) => {
        const { datalist } = this.state
        // [{},{}] -> [{},{}]
        const newDatalist = datalist.map(item => {
            if (item.id === id) {
                item.done = !item.done;
            }
            return {
                ...item
            }
        })
        this.setState({
            datalist: newDatalist
        })
    }
    removeItem = (id) => {
        // [{},{},{}] -> [{},{}]
        const newDatlist = this.state.datalist.filter(item=>item.id!==id).map(item=>({...item}))
        this.setState({
            datalist:newDatlist
        })
    }
    selectItem = ()=> {

    }
    render() {
        console.log('Todolist.render', this)
        const { datalist } = this.state;
        return (
            <context.Provider value={{ 
                add:this.addItem,
                remove: this.removeItem, 
                complete: this.completeItem 
            }}>
                <div className="todolist">
                    {
                        // Todolist: <button onClick={()=>{
                        //     this.setState({
                        //         count:this.state.count+1
                        //     })
                        // }}>count:{this.state.count}</button>
                    }
                    <TodoForm />
                    <TodoContent datalist={datalist} />
                    <TodoFoot datalist={datalist} />
                </div>
            </context.Provider>
        )
    }

}

export default Todolist

// section3/w3_VueCLI/app/src/components/Todolist/TodoList.vue
<template>
  <div class="container">
    <todo-form :add="addItem" v-on:additem="addItem" ref="todoForm"></todo-form>
    <todo-control
      :completeItems="completeItems"
      :removeItems="removeItems"
    ></todo-control>
    <todo-content :list="datalist"></todo-content>
    <todo-footer :list="datalist"></todo-footer>
  </div>
</template>
<script>
import TodoForm from "./TodoForm.vue";
import TodoControl from "./TodoControl.vue";
import TodoContent from "./TodoContent.vue";
import TodoFooter from "./TodoFooter.vue";

// 引入样式
import 'bootstrap/dist/css/bootstrap.css'
import Bus from './Bus'

export default {
  name: "TodoList",
  data() {
    Bus.$on('remove',this.removeItem)
    Bus.$on('complete',this.completeItem)
    return {
      selectIds: [],
      datalist: [
        {
          id: 1,
          todo: "定个小目标，全球旅行",
          done: true,
          addtime: Date.now(),
        },
        {
          id: 2,
          todo: "赚他一个亿津巴布韦币",
          done: false,
          addtime: Date.now() + 3600 * 1000,
        },
        {
          id: 3,
          todo: "迎娶白富美，达到人生巅峰",
          done: false,
          addtime: Date.now() + 3600 * 1000 * 5,
        },
      ],
    };
  },
  provide:function(){
    return {
        selectItem:this.selectItem,
        selectIds:this.selectIds,
        selectAll:this.selectAll
    }
},
  components: {
    TodoForm,
    TodoControl,
    TodoContent,
    TodoFooter,
  },
  methods: {
    addItem(todo) {
      const newData = {
        id: parseInt(Math.random() * 10000),
        // 需要输入框中的内容
        todo,
        done: false,
        addtime: Date.now(),
      };
      this.datalist.unshift(newData);
    },
    completeItem(id) {
      this.datalist.forEach((item) => {
        if (item.id === id) {
          item.done = !item.done;
        }
      });
    },
    removeItem(id) {
      this.datalist = this.datalist.filter((item) => item.id !== id);
    },
    selectItem(id) {
      console.log("id=", id);
      if (!this.selectIds.includes(id)) {
        this.selectIds.push(id);
      } else {
        // this.selectIds = this.selectIds.filter(item=>item!=id)
        // [1,20,3],[{},{}]
        const idx = this.selectIds.findIndex((item) => item === id);
        this.selectIds.splice(idx, 1);
      }
    },
    selectAll(all) {
      if (all) {
        // 由于是通过provide/inject传入的值，所以一下写法达不到响应式的效果
        // this.selectIds = this.datalist.map(item=>item.id)
        const ids = this.datalist.map((item) => item.id);
        this.selectIds.splice(0, this.selectIds.length);
        this.selectIds.push(...ids);
      } else {
        this.selectIds.splice(0, this.selectIds.length);
      }
    },
    // 批量完成
    completeItems() {
      this.datalist.forEach((item) => {
        if (this.selectIds.includes(item.id)) {
          item.done = true;
        }
      });
    },
    removeItems() {
      this.datalist = this.datalist.filter((item) => {
        return !this.selectIds.includes(item.id);
      });
    },
  },
};
</script>
<style>
</style>
