// section3/w6_ReactRouter/src/App copy.jsx
import React from 'react'

import { Route, HashRouter, Redirect, Switch, Link, NavLink,withRouter } from 'react-router-dom'

import Home from './views/Home'
import Login from './views/Login'
import Reg from './views/Reg'
import Manage from './views/Manage'

import './App.css'

class App extends React.Component {
    goto = (url)=>{
        this.props.history.push(url)
    }
    render() {
        console.log('App.props',this.props)
        return (
            <div className="container">
                App
                <NavLink to="/home" activeClassName="current" activeStyle={{color:'#58bc58',fontWeight:'bold'}}>首页</NavLink>
                <NavLink to="/login">登录</NavLink>
                <NavLink to="/reg" replace>注册</NavLink>

                <div>
                    <button onClick={this.goto.bind(this,'/home')}>首页</button>
                    <button onClick={this.goto.bind(this,'/login')}>登录</button>
                    <button onClick={this.goto.bind(this,'/reg')}>注册</button>

                </div>

                <Switch>
                    <Route path="/home" component={Home} />
                    <Route path="/manage" component={Manage} />
                    <Route path="/login" component={Login} />
                    <Route path="/reg">
                        <Reg />
                    </Route>
                    {/* <Route path="/notfound" render={()=><div>页面不存在</div>} /> */}
                    <Route path="/notfound">
                        <div>there is nothing hear</div>
                    </Route>
                    <Redirect from="/" to="/home" exact />
                    <Redirect from="*" to="/notfound" />
                </Switch>
            </div>
        )
    }

}



export default withRouter(App);

// section3/w3_VueRouter/app/src/App copy.vue
<template>
  <div id="app">
     <div>
      <button @click="$router.back()">回退</button>
      <button @click="$router.forward()">前进</button>
    </div>
    <!-- 路由视图显示：用于渲染路由对应的组件 -->
    <router-view></router-view>

    <router-link to="/home" tag="span" active-class="current" replace>首页</router-link>
    <router-link to="/reg">注册</router-link>
    <router-link to="/login">登录</router-link>

    <div>
      <button @click="goto('/login')">登录</button>
      <button @click="goto('/reg')">注册</button>
    </div>
  </div>
</template>

<script>

export default {
  name: 'App',
  created(){
    console.log('App',this)
  },
  methods:{
    goto(url){
      // this.$router.push(url)
      this.$router.replace(url)
    }
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
.router-link-active{color:#f00}
.current{color:#f00;font-weight:bold}
</style>
